# Generated by Django 4.1.4 on 2022-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegitables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=50, unique=True)),
                ('Price', models.FloatField()),
                ('Status', models.CharField(max_length=12)),
                ('Veg_image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
